apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: cloudgpchatbot.azurecr.io/chatbot:latest2
          ports:
            - containerPort: 80  # Change this to your application's port
          envFrom:  # Use envFrom to import all key-value pairs from the secret
            - secretRef:
                name: chatbot-secrets
                  # Define your environment variables here
      imagePullSecrets:
        - name: acr-secret
